### ISSUE TITLE
Vidplay not working!

### ISSUE THREAD

**Issue by fsmdeveloper** [Inside4ndroid/vidkey-js#1]
I'm using the latest vidsrc keys, but the hls source is still null! do you know why?

**Comment by Inside4ndroid** [comment]
It is because the api return f2cloud and not vidplay anymore     const vidplay = sources.result.find((v) => v.title.toLowerCase() === 'f2cloud');The keys are fully working and the issue your having is with due to the api you use.Sent from my Galaxy
-------- Original message --------From: Fsm Developer ***@***.***> Date: 23/06/2024  18:15  (GMT+00:00) To: Inside4ndroid/vidkey-js ***@***.***> Cc: Subscribed ***@***.***> Subject: [Inside4ndroid/vidkey-js] Vidplay not working! (Issue #1) 
I'm using the latest vidsrc keys, but the hls source is still null! do you know why?

**Comment by Inside4ndroid** [comment]
> I'm using the latest vidsrc keys, but the hls source is still null! do you know why?

it is not the keys thats the issue it is the api you are using. the json return f2cloud rather than vidplay so it will throw a 404 error or be blank.

if you are hosting the vidsrc api yourself i can help you fix it.

**Comment by fsmdeveloper** [comment]
Yeah, bro, I am using a Digital Ocean droplet. It's my personal droplet. Please tell me how I can fix that issue

**Comment by fsmdeveloper** [comment]
`[VidSrcExtractor] No source found for "Vidplay"
Available Sources: F2Cloud, Filemoon`

getting this error. I'm using https://github.com/Ciarands/vidsrc-to-resolver

**Comment by fsmdeveloper** [comment]
Also, I'm facing a weird issue with the Filemoon source. If I get the HLS URL from localhost/PC, it works, but if I get the Filemoon source from the VPS droplet, it does not work

**Comment by Inside4ndroid** [comment]
okay so to fix the issue with 

[VidSrcExtractor] No source found for "Vidplay" Available Sources: F2Cloud, Filemoon

in the vidsrc.py add F2Cloud to line 14

SUPPORTED_SOURCES = ["Vidplay", "Filemoon"]

like this 

SUPPORTED_SOURCES = ["F2Cloud", "Vidplay", "Filemoon"]


and for Filemoon i will have to look into it but i believe that is an issue where the hls has to be passed or used with a proxy. But i could be wrong as i use a javascript version for vidplay only.

**Comment by Inside4ndroid** [comment]
if not you can take a look at my javascript integration in the newly created repo here :

https://github.com/Inside4ndroid/vidsrc-api-js

**Comment by fsmdeveloper** [comment]
Thanks for your kind information bro.

I have changed the line 14. but still getting an error.

$ python vidsrc.py
? Select Source F2Cloud
? Fetch Subtitles No
? Search Media:  king kong
? ? Select Media 2. King Kong (ডিসেম্বর 12, 2005)
[>] Requesting https://vidsrc.to/embed/movie/254...
**[VidSrcExtractor] Sorry, this doesnt currently support "F2Cloud" :(**
[VidSrcExtractor] (if you create an issue and ask really nicely ill maybe look into reversing it though)...
? Could not find sources for F2Cloud, would you like to try scraping Vidplay?

**Comment by fsmdeveloper** [comment]
> if not you can take a look at my javascript integration in the newly created repo here :
> 
> https://github.com/Inside4ndroid/vidsrc-api-js

I'm trying your fork. thanks bro!

**Comment by fsmdeveloper** [comment]
YES! The script from https://github.com/Inside4ndroid/vidsrc-api-js is working. However, it is not working with Vercel

**Comment by Inside4ndroid** [comment]
> YES! The script from https://github.com/Inside4ndroid/vidsrc-api-js is working. However, it is not working with Vercel

ah i had an issue with vercel but if i remember correctly i had to goto vercel projects settings then general and change the Node.js Version option to 20 as it defaulted to 18.

**Comment by Inside4ndroid** [comment]
i will close this for now. but if you want more help etc you can get me on new discord here 

https://discord.gg/xVJqpJtB

**Comment by fsmdeveloper** [comment]
Thanks bro! You helped me a lot! I'll knock you on discord.
